# Use the official NGINX base image
FROM nginx:latest

# Optionally, you can copy custom configuration files
# COPY nginx.conf /etc/nginx/nginx.conf

# Expose the default HTTP port
EXPOSE 80

# Start NGINX when the container starts
CMD ["nginx", "-g", "daemon off;"]

